import{QUALITY}from'../config';
const MAX_WAVES=12,MAX_PARTICLES=90,SEG=96;
function shader(gl,type,src){const s=gl.createShader(type);if(!s)throw Error('WebGL shader unavailable');gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error('WebGL shader compile failed: '+gl.getShaderInfoLog(s));return s}
function program(gl,vs,fs){const p=gl.createProgram();if(!p)throw Error('WebGL program unavailable');gl.attachShader(p,shader(gl,gl.VERTEX_SHADER,vs));gl.attachShader(p,shader(gl,gl.FRAGMENT_SHADER,fs));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error('WebGL program link failed: '+gl.getProgramInfoLog(p));return p}
function loc(gl,p,n){const l=gl.getAttribLocation(p,n);if(l<0)throw Error('WebGL attribute missing: '+n);return l}
const v2='attribute vec2 a;uniform vec2 uRes;void main(){vec2 p=a/uRes*2.0-1.0;gl_Position=vec4(p.x,-p.y,0,1);}';
const bgVs='attribute vec2 a;varying vec2 v;void main(){v=a*.5+.5;gl_Position=vec4(a,0,1);}';
const bgFs='precision mediump float;varying vec2 v;uniform float uTime;uniform vec2 uRes;uniform int uWaveCount;uniform vec4 uWaves[12];void main(){vec2 p=v*uRes;float w=0.0;for(int i=0;i<12;i++){if(i>=uWaveCount)break;vec4 a=uWaves[i];float d=distance(p,a.xy);w+=exp(-pow(abs(d-a.z)/(a.w+1.0),2.0))*.26;}float rip=sin(p.x*.045+uTime*1.4)*.025+sin(p.y*.055-uTime*1.1)*.018;vec3 col=mix(vec3(.006,.025,.055),vec3(.02,.16,.24),v.y+rip+w);col+=vec3(.06,.55,.75)*w;gl_FragColor=vec4(col,1.0);}';
const colorFs='precision mediump float;uniform vec4 uColor;void main(){gl_FragColor=uColor;}';
const pointVs='attribute vec2 a;uniform vec2 uRes;uniform float uSize;void main(){vec2 p=a/uRes*2.0-1.0;gl_Position=vec4(p.x,-p.y,0,1);gl_PointSize=uSize;}';
export class WebGLView{w=1;h=1;dpr=1;ring=new Float32Array((SEG+1)*2);circle=new Float32Array((SEG+2)*2);tmp=new Float32Array(1024);constructor(canvas){this.canvas=canvas;const gl=(canvas.getContext('webgl',{alpha:false,antialias:false,powerPreference:'high-performance'})||canvas.getContext('experimental-webgl',{alpha:false}));if(!gl)throw Error('WebGL unavailable');this.gl=gl;this.bg=program(gl,bgVs,bgFs);this.color=program(gl,v2,colorFs);this.point=program(gl,pointVs,colorFs);const b=gl.createBuffer();if(!b)throw Error('WebGL buffer unavailable');this.buf=b;gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.disable(gl.DEPTH_TEST);this.selfTest()}
selfTest(){const gl=this.gl;gl.useProgram(this.color);gl.bindBuffer(gl.ARRAY_BUFFER,this.buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([0,0,1,0]),gl.DYNAMIC_DRAW);const a=loc(gl,this.color,'a');gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0);gl.uniform2f(gl.getUniformLocation(this.color,'uRes'),1,1);gl.uniform4f(gl.getUniformLocation(this.color,'uColor'),0,0,0,0);gl.drawArrays(gl.LINES,0,2);const err=gl.getError();if(err!==gl.NO_ERROR)throw Error('WebGL draw unavailable: '+err)}
resize(w,h,q){this.w=w;this.h=h;this.dpr=Math.min(devicePixelRatio||1,QUALITY[q].dpr);this.canvas.width=Math.max(1,Math.floor(w*this.dpr));this.canvas.height=Math.max(1,Math.floor(h*this.dpr));this.canvas.style.width=w+'px';this.canvas.style.height=h+'px';this.gl.viewport(0,0,this.canvas.width,this.canvas.height)}
setCommon(p){const gl=this.gl;gl.useProgram(p);gl.bindBuffer(gl.ARRAY_BUFFER,this.buf);const a=loc(gl,p,'a');gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0);gl.uniform2f(gl.getUniformLocation(p,'uRes'),this.w,this.h)}
drawBg(world,t,q){const gl=this.gl;gl.useProgram(this.bg);gl.bindBuffer(gl.ARRAY_BUFFER,this.buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,1,1]),gl.STATIC_DRAW);const a=loc(gl,this.bg,'a');gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0);gl.uniform1f(gl.getUniformLocation(this.bg,'uTime'),t*.001);gl.uniform2f(gl.getUniformLocation(this.bg,'uRes'),this.w,this.h);const ws=world.waves.slice(0,Math.min(MAX_WAVES,QUALITY[q].waves));gl.uniform1i(gl.getUniformLocation(this.bg,'uWaveCount'),ws.length);const data=new Float32Array(MAX_WAVES*4);ws.forEach((w,i)=>data.set([w.originX,w.originY,w.radius,w.width],i*4));gl.uniform4fv(gl.getUniformLocation(this.bg,'uWaves[0]'),data);gl.drawArrays(gl.TRIANGLE_STRIP,0,4)}
drawLine(points,count,rgba,mode,lineWidth=1){const gl=this.gl;this.setCommon(this.color);gl.bufferData(gl.ARRAY_BUFFER,points.subarray(0,count*2),gl.DYNAMIC_DRAW);gl.uniform4f(gl.getUniformLocation(this.color,'uColor'),rgba[0],rgba[1],rgba[2],rgba[3]);gl.lineWidth(lineWidth);gl.drawArrays(mode,0,count)}
render(world,t,q){const gl=this.gl;gl.viewport(0,0,this.canvas.width,this.canvas.height);this.drawBg(world,t,q);for(const g of world.glass){this.tmp.set([g.x1,g.y1,g.x2,g.y2]);this.drawLine(this.tmp,2,[.78,1,1,.48],gl.LINES,3)}for(const e of world.waves.slice(0,QUALITY[q].waves)){for(let i=0;i<=SEG;i++){const a=i/SEG*Math.PI*2,o=i*2;this.ring[o]=e.originX+Math.cos(a)*e.radius;this.ring[o+1]=e.originY+Math.sin(a)*e.radius}const fade=Math.max(0,1-e.age/e.life);this.drawLine(this.ring,SEG+1,e.kind==='glass'?[.72,.96,1,fade*.78]:[.35,.92,1,fade*.82],gl.LINE_STRIP,2)}for(const b of world.beacons){this.circle[0]=b.x;this.circle[1]=b.y;const r=b.radius*(2.6+b.flash*.9);for(let i=0;i<=SEG;i++){const a=i/SEG*Math.PI*2,o=(i+1)*2;this.circle[o]=b.x+Math.cos(a)*r;this.circle[o+1]=b.y+Math.sin(a)*r}this.drawLine(this.circle,SEG+2,[.35,.9,1,.20+b.flash*.25],gl.TRIANGLE_FAN);for(let i=0;i<=SEG;i++){const a=i/SEG*Math.PI*2,o=i*2;this.ring[o]=b.x+Math.cos(a)*b.radius;this.ring[o+1]=b.y+Math.sin(a)*b.radius}this.drawLine(this.ring,SEG+1,[1,1,.88,.95],gl.TRIANGLE_FAN)}let n=0;for(const p of world.particles.slice(0,MAX_PARTICLES)){this.tmp[n++]=p.x;this.tmp[n++]=p.y}if(n){this.setCommon(this.point);gl.bufferData(gl.ARRAY_BUFFER,this.tmp.subarray(0,n),gl.DYNAMIC_DRAW);gl.uniform4f(gl.getUniformLocation(this.point,'uColor'),.75,1,1,.9);gl.uniform1f(gl.getUniformLocation(this.point,'uSize'),Math.max(2,3*this.dpr));gl.drawArrays(gl.POINTS,0,n/2)}}}
